
name: example
description: Demonstrates how to use the legacy_gantt_chart plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  legacy_context_menu: ^2.1.2
  legacy_gantt_chart:
    path: ../
  legacy_timeline_scrubber: ^2.0.0
  provider: ^6.1.2

  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  legacy_tree_grid: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
