
name: example
description: Demonstrates how to use the legacy_gantt_chart plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  legacy_context_menu: ^2.1.2
  legacy_gantt_chart:
    path: ../
  legacy_gantt_protocol: ^1.0.6
  legacy_timeline_scrubber: ^2.0.0
  provider: ^6.1.2

  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  legacy_tree_grid: ^0.11.0
  sqlite_crdt: ^3.0.0
  uuid: ^4.0.0
  path_provider: ^2.1.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.1
  sqflite_common_ffi_web: ^1.1.0
  web_socket_channel: ^3.0.3
  http: ^1.6.0
  synchronized: ^3.3.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  stream_channel: ^2.1.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true