name: legacy_gantt_chart
description: A flexible and performant Gantt chart widget for Flutter. Supports interactive drag-and-drop, resizing, dynamic data loading, and extensive theming.
version: 3.1.5
license: MIT
homepage: https://github.com/barneysspeedshop/legacy_gantt_chart
repository: https://github.com/barneysspeedshop/legacy_gantt_chart
issue_tracker: https://github.com/barneysspeedshop/legacy_gantt_chart/issues

topics:
  - gantt
  - chart
  - schedule
  - project-management
  - timeline

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  legacy_timeline_scrubber: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

screenshots:
  - description: 'Legacy Gantt Chart - screenshot 1'
    path: assets/example.png